name: Deploy React App to GitHub Pages


on:
  push:
    branches:
      - main # Cambia a 'master' si esa es tu rama principal
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Puedes ajustar la versión de Node.js si lo necesitas

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Asegúrate de que esta sea la carpeta de salida de tu build
          publish_branch: gh-pages # La rama donde se desplegará la aplicación


